apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-account
  namespace: backend
  labels:
    app: cluster-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-account
  template:
    metadata:
      labels:
        app: cluster-account
    spec:
      containers:
        - name: cluster-account
          image: pashamad/cluster-account-srv:latest
          ports:
            - containerPort: 11223
