apiVersion: v1
kind: Service
metadata:
  name: cluster-account
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11223
      targetPort: 11223
  selector:
    app: cluster-account
  type: LoadBalancer
