apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-coinsrate
  namespace: backend
  labels:
    app: cluster-coinsrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-coinsrate
  template:
    metadata:
      labels:
        app: cluster-coinsrate
    spec:
      containers:
        - name: cluster-coinsrate
          image: pashamad/cluster-coinsrate-srv:latest
          ports:
            - containerPort: 11557
