apiVersion: v1
kind: Service
metadata:
  name: cluster-coinsrate
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11557
      targetPort: 11557
  selector:
    app: cluster-coinsrate
  type: LoadBalancer
