apiVersion: v1
kind: Service
metadata:
  name: cluster-eth-listener
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11445
      targetPort: 11445
  selector:
    app: cluster-eth-listener
  type: LoadBalancer
