apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-eth-listener
  namespace: backend
  labels:
    app: cluster-eth-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-eth-listener
  template:
    metadata:
      labels:
        app: cluster-eth-listener
    spec:
      containers:
        - name: cluster-eth-listener
          image: pashamad/cluster-eth-listener-srv:latest
          ports:
            - containerPort: 11445
