apiVersion: v1
kind: Service
metadata:
  name: cluster-sol-listener
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11446
      targetPort: 11446
  selector:
    app: cluster-sol-listener
  type: LoadBalancer
