apiVersion: v1
kind: Service
metadata:
  name: cluster-coinsrate
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11556
      targetPort: 11556
  selector:
    app: cluster-coinsrate
  type: LoadBalancer
