apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-writer
  namespace: backend
  labels:
    app: cluster-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-writer
  template:
    metadata:
      labels:
        app: cluster-writer
    spec:
      containers:
        - name: cluster-writer
          image: pashamad/cluster-writer-srv:latest
          ports:
            - containerPort: 11334
