apiVersion: v1
kind: Service
metadata:
  name: cluster-writer
  namespace: backend
spec:
  ports:
    - name: grpc
      port: 11334
      targetPort: 11334
  selector:
    app: cluster-writer
  type: LoadBalancer
