// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: writer/writer.proto

package writer

import (
	response "github.com/truekupo/cluster/common/interfaces/messages/response"
	types "github.com/truekupo/cluster/common/interfaces/messages/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  types.CoinCode `protobuf:"varint,1,opt,name=symbol,proto3,enum=types.CoinCode" json:"symbol,omitempty"`
	Address string         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetSymbol() types.CoinCode {
	if x != nil {
		return x.Symbol
	}
	return types.CoinCode_BTC
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    string           `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	RetStatus *response.Status `protobuf:"bytes,2,opt,name=ret_status,json=retStatus,proto3" json:"ret_status,omitempty"`
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetBalanceResponse) GetRetStatus() *response.Status {
	if x != nil {
		return x.RetStatus
	}
	return nil
}

type SendFromToRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      types.CoinCode `protobuf:"varint,1,opt,name=symbol,proto3,enum=types.CoinCode" json:"symbol,omitempty"`
	FromAddr    string         `protobuf:"bytes,2,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	ToAddr      string         `protobuf:"bytes,3,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	FromPrivate string         `protobuf:"bytes,4,opt,name=from_private,json=fromPrivate,proto3" json:"from_private,omitempty"`
	Amount      string         `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SendFromToRequest) Reset() {
	*x = SendFromToRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFromToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFromToRequest) ProtoMessage() {}

func (x *SendFromToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFromToRequest.ProtoReflect.Descriptor instead.
func (*SendFromToRequest) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{2}
}

func (x *SendFromToRequest) GetSymbol() types.CoinCode {
	if x != nil {
		return x.Symbol
	}
	return types.CoinCode_BTC
}

func (x *SendFromToRequest) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *SendFromToRequest) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *SendFromToRequest) GetFromPrivate() string {
	if x != nil {
		return x.FromPrivate
	}
	return ""
}

func (x *SendFromToRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SendFromToResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *types.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	RetStatus   *response.Status   `protobuf:"bytes,2,opt,name=ret_status,json=retStatus,proto3" json:"ret_status,omitempty"`
}

func (x *SendFromToResponse) Reset() {
	*x = SendFromToResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFromToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFromToResponse) ProtoMessage() {}

func (x *SendFromToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFromToResponse.ProtoReflect.Descriptor instead.
func (*SendFromToResponse) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{3}
}

func (x *SendFromToResponse) GetTransaction() *types.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SendFromToResponse) GetRetStatus() *response.Status {
	if x != nil {
		return x.RetStatus
	}
	return nil
}

type GetTxStatusByHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol types.CoinCode `protobuf:"varint,1,opt,name=symbol,proto3,enum=types.CoinCode" json:"symbol,omitempty"`
	TxHash string         `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *GetTxStatusByHashRequest) Reset() {
	*x = GetTxStatusByHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxStatusByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxStatusByHashRequest) ProtoMessage() {}

func (x *GetTxStatusByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxStatusByHashRequest.ProtoReflect.Descriptor instead.
func (*GetTxStatusByHashRequest) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{4}
}

func (x *GetTxStatusByHashRequest) GetSymbol() types.CoinCode {
	if x != nil {
		return x.Symbol
	}
	return types.CoinCode_BTC
}

func (x *GetTxStatusByHashRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetTxStatusByHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    types.TxStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=types.TxStatus" json:"status,omitempty"`
	RetStatus *response.Status `protobuf:"bytes,2,opt,name=ret_status,json=retStatus,proto3" json:"ret_status,omitempty"`
}

func (x *GetTxStatusByHashResponse) Reset() {
	*x = GetTxStatusByHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writer_writer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxStatusByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxStatusByHashResponse) ProtoMessage() {}

func (x *GetTxStatusByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxStatusByHashResponse.ProtoReflect.Descriptor instead.
func (*GetTxStatusByHashResponse) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{5}
}

func (x *GetTxStatusByHashResponse) GetStatus() types.TxStatus {
	if x != nil {
		return x.Status
	}
	return types.TxStatus_NEW
}

func (x *GetTxStatusByHashResponse) GetRetStatus() *response.Status {
	if x != nil {
		return x.RetStatus
	}
	return nil
}

var File_writer_writer_proto protoreflect.FileDescriptor

var file_writer_writer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x1a, 0x20, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x5d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66,
	0x72, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x7b, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f,
	0x0a, 0x0a, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x5c, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x79,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x75, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x72, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0xfb, 0x01, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x12, 0x19, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x12, 0x19, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x2e, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_writer_writer_proto_rawDescOnce sync.Once
	file_writer_writer_proto_rawDescData = file_writer_writer_proto_rawDesc
)

func file_writer_writer_proto_rawDescGZIP() []byte {
	file_writer_writer_proto_rawDescOnce.Do(func() {
		file_writer_writer_proto_rawDescData = protoimpl.X.CompressGZIP(file_writer_writer_proto_rawDescData)
	})
	return file_writer_writer_proto_rawDescData
}

var file_writer_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_writer_writer_proto_goTypes = []interface{}{
	(*GetBalanceRequest)(nil),         // 0: writer.GetBalanceRequest
	(*GetBalanceResponse)(nil),        // 1: writer.GetBalanceResponse
	(*SendFromToRequest)(nil),         // 2: writer.SendFromToRequest
	(*SendFromToResponse)(nil),        // 3: writer.SendFromToResponse
	(*GetTxStatusByHashRequest)(nil),  // 4: writer.GetTxStatusByHashRequest
	(*GetTxStatusByHashResponse)(nil), // 5: writer.GetTxStatusByHashResponse
	(types.CoinCode)(0),               // 6: types.CoinCode
	(*response.Status)(nil),           // 7: response.Status
	(*types.Transaction)(nil),         // 8: types.Transaction
	(types.TxStatus)(0),               // 9: types.TxStatus
}
var file_writer_writer_proto_depIdxs = []int32{
	6,  // 0: writer.GetBalanceRequest.symbol:type_name -> types.CoinCode
	7,  // 1: writer.GetBalanceResponse.ret_status:type_name -> response.Status
	6,  // 2: writer.SendFromToRequest.symbol:type_name -> types.CoinCode
	8,  // 3: writer.SendFromToResponse.transaction:type_name -> types.Transaction
	7,  // 4: writer.SendFromToResponse.ret_status:type_name -> response.Status
	6,  // 5: writer.GetTxStatusByHashRequest.symbol:type_name -> types.CoinCode
	9,  // 6: writer.GetTxStatusByHashResponse.status:type_name -> types.TxStatus
	7,  // 7: writer.GetTxStatusByHashResponse.ret_status:type_name -> response.Status
	0,  // 8: writer.WriterService.GetBalanceOf:input_type -> writer.GetBalanceRequest
	2,  // 9: writer.WriterService.SendFromTo:input_type -> writer.SendFromToRequest
	4,  // 10: writer.WriterService.GetTxStatusByHash:input_type -> writer.GetTxStatusByHashRequest
	1,  // 11: writer.WriterService.GetBalanceOf:output_type -> writer.GetBalanceResponse
	3,  // 12: writer.WriterService.SendFromTo:output_type -> writer.SendFromToResponse
	5,  // 13: writer.WriterService.GetTxStatusByHash:output_type -> writer.GetTxStatusByHashResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_writer_writer_proto_init() }
func file_writer_writer_proto_init() {
	if File_writer_writer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_writer_writer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writer_writer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writer_writer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFromToRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writer_writer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFromToResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writer_writer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxStatusByHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writer_writer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxStatusByHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_writer_writer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writer_writer_proto_goTypes,
		DependencyIndexes: file_writer_writer_proto_depIdxs,
		MessageInfos:      file_writer_writer_proto_msgTypes,
	}.Build()
	File_writer_writer_proto = out.File
	file_writer_writer_proto_rawDesc = nil
	file_writer_writer_proto_goTypes = nil
	file_writer_writer_proto_depIdxs = nil
}
