// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: coinsrate/coinsrate.proto

package coinsrate

import (
	response "github.com/truekupo/cluster/common/interfaces/messages/response"
	types "github.com/truekupo/cluster/common/interfaces/messages/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixTm   int64          `protobuf:"varint,1,opt,name=UnixTm,proto3" json:"UnixTm,omitempty"`
	Coin     types.CoinCode `protobuf:"varint,2,opt,name=Coin,proto3,enum=types.CoinCode" json:"Coin,omitempty"`
	Currency types.CoinCode `protobuf:"varint,3,opt,name=Currency,proto3,enum=types.CoinCode" json:"Currency,omitempty"`
	Rate     string         `protobuf:"bytes,4,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *Rate) Reset() {
	*x = Rate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coinsrate_coinsrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_coinsrate_coinsrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_coinsrate_coinsrate_proto_rawDescGZIP(), []int{0}
}

func (x *Rate) GetUnixTm() int64 {
	if x != nil {
		return x.UnixTm
	}
	return 0
}

func (x *Rate) GetCoin() types.CoinCode {
	if x != nil {
		return x.Coin
	}
	return types.CoinCode_BTC
}

func (x *Rate) GetCurrency() types.CoinCode {
	if x != nil {
		return x.Currency
	}
	return types.CoinCode_BTC
}

func (x *Rate) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

type LastRatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coins    []types.CoinCode `protobuf:"varint,1,rep,packed,name=Coins,proto3,enum=types.CoinCode" json:"Coins,omitempty"`
	Currency types.CoinCode   `protobuf:"varint,2,opt,name=Currency,proto3,enum=types.CoinCode" json:"Currency,omitempty"`
}

func (x *LastRatesRequest) Reset() {
	*x = LastRatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coinsrate_coinsrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastRatesRequest) ProtoMessage() {}

func (x *LastRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coinsrate_coinsrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastRatesRequest.ProtoReflect.Descriptor instead.
func (*LastRatesRequest) Descriptor() ([]byte, []int) {
	return file_coinsrate_coinsrate_proto_rawDescGZIP(), []int{1}
}

func (x *LastRatesRequest) GetCoins() []types.CoinCode {
	if x != nil {
		return x.Coins
	}
	return nil
}

func (x *LastRatesRequest) GetCurrency() types.CoinCode {
	if x != nil {
		return x.Currency
	}
	return types.CoinCode_BTC
}

type LastRatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rates     []*Rate          `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	RetStatus *response.Status `protobuf:"bytes,2,opt,name=ret_status,json=retStatus,proto3" json:"ret_status,omitempty"`
}

func (x *LastRatesResponse) Reset() {
	*x = LastRatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coinsrate_coinsrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastRatesResponse) ProtoMessage() {}

func (x *LastRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coinsrate_coinsrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastRatesResponse.ProtoReflect.Descriptor instead.
func (*LastRatesResponse) Descriptor() ([]byte, []int) {
	return file_coinsrate_coinsrate_proto_rawDescGZIP(), []int{2}
}

func (x *LastRatesResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *LastRatesResponse) GetRetStatus() *response.Status {
	if x != nil {
		return x.RetStatus
	}
	return nil
}

var File_coinsrate_coinsrate_proto protoreflect.FileDescriptor

var file_coinsrate_coinsrate_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f, 0x69, 0x6e,
	0x73, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x69,
	0x6e, 0x73, 0x72, 0x61, 0x74, 0x65, 0x1a, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x6e, 0x69, 0x78, 0x54, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x6e, 0x69, 0x78, 0x54, 0x6d, 0x12, 0x23, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x22, 0x66, 0x0a, 0x10, 0x4c,
	0x61, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x22, 0x6b, 0x0a, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x72,
	0x61, 0x74, 0x65, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x05, 0x72, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0x5c, 0x0a, 0x10, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x61,
	0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x72, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coinsrate_coinsrate_proto_rawDescOnce sync.Once
	file_coinsrate_coinsrate_proto_rawDescData = file_coinsrate_coinsrate_proto_rawDesc
)

func file_coinsrate_coinsrate_proto_rawDescGZIP() []byte {
	file_coinsrate_coinsrate_proto_rawDescOnce.Do(func() {
		file_coinsrate_coinsrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_coinsrate_coinsrate_proto_rawDescData)
	})
	return file_coinsrate_coinsrate_proto_rawDescData
}

var file_coinsrate_coinsrate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coinsrate_coinsrate_proto_goTypes = []interface{}{
	(*Rate)(nil),              // 0: coinsrate.Rate
	(*LastRatesRequest)(nil),  // 1: coinsrate.LastRatesRequest
	(*LastRatesResponse)(nil), // 2: coinsrate.LastRatesResponse
	(types.CoinCode)(0),       // 3: types.CoinCode
	(*response.Status)(nil),   // 4: response.Status
}
var file_coinsrate_coinsrate_proto_depIdxs = []int32{
	3, // 0: coinsrate.Rate.Coin:type_name -> types.CoinCode
	3, // 1: coinsrate.Rate.Currency:type_name -> types.CoinCode
	3, // 2: coinsrate.LastRatesRequest.Coins:type_name -> types.CoinCode
	3, // 3: coinsrate.LastRatesRequest.Currency:type_name -> types.CoinCode
	0, // 4: coinsrate.LastRatesResponse.rates:type_name -> coinsrate.Rate
	4, // 5: coinsrate.LastRatesResponse.ret_status:type_name -> response.Status
	1, // 6: coinsrate.CoinsRateService.LastRates:input_type -> coinsrate.LastRatesRequest
	2, // 7: coinsrate.CoinsRateService.LastRates:output_type -> coinsrate.LastRatesResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_coinsrate_coinsrate_proto_init() }
func file_coinsrate_coinsrate_proto_init() {
	if File_coinsrate_coinsrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coinsrate_coinsrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coinsrate_coinsrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastRatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coinsrate_coinsrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastRatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coinsrate_coinsrate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coinsrate_coinsrate_proto_goTypes,
		DependencyIndexes: file_coinsrate_coinsrate_proto_depIdxs,
		MessageInfos:      file_coinsrate_coinsrate_proto_msgTypes,
	}.Build()
	File_coinsrate_coinsrate_proto = out.File
	file_coinsrate_coinsrate_proto_rawDesc = nil
	file_coinsrate_coinsrate_proto_goTypes = nil
	file_coinsrate_coinsrate_proto_depIdxs = nil
}
